name: Validate FAQ Frontmatter

on:
  pull_request:
    paths:
      - 'faqs/**'  # Trigger only for changes in the 'faqs' directory

jobs:
  validate-faq:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Python environment
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: pip install pyyaml

      # Step 4: Run the validation script and capture output
      - name: Run Validation
        id: validation
        run: |
          python scripts/validate_faq.py > validation_errors.log 2>&1

      # Step 5: Post a comment to the PR if validation fails
      - name: Post Comment on PR if Validation Fails
        if: failure()  # Run only if the validation step fails
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const validationErrors = fs.readFileSync('validation_errors.log', 'utf8');
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: `🚨 **Validation Failed**:\n\n${validationErrors}`
            });
