name: Validate FAQ

on:
  push:
    branches: [ "main" ] # TODO: make it run only when not main or dev branch
    paths:
    - insights/**
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  validate:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
      
      - uses: datopian/find-monorepo
        name: Validate FAQ
        with:
        - # TODO: pass the vars
        - # TODO: make sure to set status so that we can block merge of this PR
        - # TODO: (optional) Make this GitHub action post a comment on the PR if it failed, with the validation error
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
